<div id="webpos_popups">
<?php $currencySymbol = Mage::helper('webpos')->getCurrencySymbol(); ?>
<div class="webpos_overlay dark_overlay" id="webpos_dark_overlay" onclick='overlayClicked()'></div>
<div class='webpos_overlay' id='webpos_overlay' onclick='overlayClicked()'></div>
<div id="edit_cart_item_popup" class=" col-lg-3 col-md-3 col-sm-3 col-xs-3">
    <div class="edit_cart_item_popup">
        <div class='product_tab'>
            <div class='product_info'>
                <img src='' class='product_image' id='editpopup_product_image'/>
                <div class='product_name' id='editpopup_product_name'></div>
                <div class='product_message' id='editpopup_product_message'></div>
            </div>
            <div class='product_qty'>
                <div class='bt_desc_qty'><button id='bt_desc_qty' type="button" class="btn btn-warning"><?php echo $this->__('-'); ?></button></div>
                <div class='qty_value'><input value='0' id='editpopup_product_qty' onkeypress="checkQty(event);"/></div>
                <div class='bt_inc_qty'><button id='bt_inc_qty' type="button" class="btn btn-warning"><?php echo $this->__('+'); ?></button></div>
            </div>

            <div  class="edit-price common" onclick="" style="text-align: left">
                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>
                    <button id="btn-custom" class="btn nochoose" type="button">Custom Price</button>
                </div>

                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>

                    <button id="btn-discount" class="btn choose" type="button">Discount</button>
                </div>
            </div>
            <div class='custom_price common' onclick='showCustomPriceTab()'>
                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6 label-type' style="text-align: left"><?php echo $this->__('Discount'); ?></div>
                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6 item-subtotal'>
                    <span><?php //echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();    ?></span>
                    <div class='webpos_item_subtotal'><?php echo Mage::helper('core')->currency(0, true, false); ?></div>
                </div>
            </div>
            <div  class="edit-option common" onclick="" style="text-align: left">
                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6' style="text-align: left"><?php echo $this->__('Options'); ?></div>
                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6 options'>

                </div>
            </div>
        </div>
        <div class='custom_price_tab'>
            <form class="form">
                <div class="col custom-price">
                    <div class="back-option col-lg-1 col-md-1 col-sm-1 col-xs-1" onclick='hideCustomPriceTab()'>x</div>
                    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7"><h2 class="label-type"><?php echo $this->__('Discount') ?></h2></div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><button type="button" class="btn btn-done" id="change-price"><?php echo $this->__('Done') ?></button></div>
                </div>
                <div class="col discount-type">
                    <div class="type col-lg-6 col-md-6 col-sm-6 col-xs-6"><?php echo $this->__('Type') ?></div>
                    <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <button type="button" class="btn btn1" id="btn-percent">%</button>
                        <button type="button" class="btn btn2" id="btn-dollor"><?php echo $currencySymbol; ?></button>
                    </div>
                </div>
                <div class="col input-amount">
                    <div class="amount col-lg-3 col-md-3 col-sm-3 col-xs-3"><?php echo $this->__('Amount') ?></div>
                    <div class=" col-lg-9 col-md-9 col-sm-9 col-xs-9"><input type="text"
                                                                             onkeydown ="keyCheckCustomPrice(event);
                                                                                     if (event.keyCode == 8 || event.keyCode == 46)
                                                                                         return false;" onkeypress="formatInputPriceCustomPrice(event);
                                                                                                 return false" placeholder="<?php echo Mage::helper('core')->currency(0, true, false); ?>" class="input-text form-control"
                                                                             id="discount-amount"/></div>
                </div>
                <div class="form-custom">
                    <ul>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="1">1</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="2">2</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="3">3</button>
                        </li>
                    </ul>
                    <ul>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="4">4</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="5">5</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="6">6</button>
                        </li>
                    </ul>
                    <ul>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="7">7</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="8">8</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="9">9</button>
                        </li>
                    </ul>
                    <ul>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default clear-number" id="clear-number" ></button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="0">0</button>
                        </li>
                        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <button type="button" class="btn btn-default" value="00">00</button>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
        <div id='edit_options_tab'>

        </div>
    </div>
</div>
<div class="bg-loading-ajax" id='bg_ajax_loader'>
    <div class="img-ajax"></div>
</div>
<div id='hiddenArea' class='hide'>
    <div id='hiddenContainer' class='hide'>
    </div>
    <input type='hidden' id='upload_file_path' value=''/>
</div>
<div class="popup-customer col-lg-4 col-md-4 col-sm-4 col-xs-4" id="popup-customer" style="display: none">
    <div class="popup-content">
        <div class="btn-create-customer">
            <button id="btn-create" onclick="showAddCustomer()" type="button" class="btn btn-warning">Create Customer</button>
        </div>
        <form id="customer_search_form" action="" method="" onsubmit="return false;">
            <div class="search">
                <input type="text" onkeyup="searchCustomerOffline(this)" class="input-text form-control" placeholder="Search" id="search_customer" onchange="searchCustomer()" />
            </div>
        </form>
        <div id="customer_search_autocomplete_message"></div>
        <div id="customer_search_autocomplete" class="autocomplete">
            <ul id='customer_list' onscroll="loadMoreCustomer()">
                <?php
                $session = Mage::getSingleton('webpos/session');
                $userId = $session->getId();
                if (isset($userId) && ($userId > 0)) { //vietdq prevent show customer when not login


                    $customers = Mage::getResourceModel('customer/customer_collection')->addAttributeToSelect('*')
                        ->joinAttribute('telephone', 'customer_address/telephone', 'default_billing', null, 'left')
                        ->addExpressionAttributeToSelect('full_name', 'LOWER(CONCAT({{firstname}},"",{{lastname}}))', array('firstname', 'lastname'))
                        ->setPageSize(30)   //lam theo yeu cau cua Lap
                    ;
                    foreach ($customers as $customer):
                        ?>
                        <li id="customer_result_<?php echo $customer->getId(); ?>" customerid="<?php echo $customer->getId(); ?>" firstname="<?php echo $customer->getFirstname(); ?>" lastname="<?php echo $customer->getLastname(); ?>" email="<?php echo $customer->getEmail(); ?>" onclick="addCustomerToCart(<?php echo $customer->getId() ?>);" style="width:100%; float:left; cursor: pointer" class="email-customer col-lg-6 col-md-6">
                            <span style="float:left; width: 45%;"><?php echo $customer->getFirstname() . " " . $customer->getLastname(); ?></span>
                            <span style="float:right; width: 54%;"><a href="mailto:<?php echo $customer->getEmail(); ?>"><?php echo $customer->getEmail(); ?></a></span></li>
                    <?php endforeach; ?>
                <?php }?>
            </ul>
        </div>

    </div>
</div>
<?php
$shipping_carrier_name = Mage::getModel('webpos/shipping_carrier_webposshipping')->getCarrierName();
$shipping_method_name = Mage::getModel('webpos/shipping_carrier_webposshipping')->getMethodName();
$shipping_methodCode = Mage::getModel('webpos/shipping_carrier_webposshipping')->getMethodCode();
$shipping_method_price = Mage::getModel('webpos/shipping_carrier_webposshipping')->getMethodPrice();
$cash_title = Mage::helper('webpos/payment')->getCashMethodTitle();
$cc_title = Mage::helper('webpos/payment')->getCcMethodTitle();
?>
<script type='text/javascript'>
    var appliedShipping = false;
    function getShippingPrice(){
        return parseFloat('<?php echo $shipping_method_price;?>');
    }

    function getShippingTitle() {
        var shipping_title = '<?php echo $this->__($shipping_method_name); ?>';
        return shipping_title;
    }
    function getShippingHtml() {
        var shipping = '<dl class="sp-methods">\
                <dt><?php echo $this->__($shipping_carrier_name); ?></dt>\
        <dd>\
            <ul>\
                                <li onclick=\'selectShippingMethod(save_data_url,"<?php echo $shipping_methodCode; ?>","<?php echo $shipping_method_name; ?>")\'>\
                                        <input name="shipping_method" type="radio" value="<?php echo $shipping_methodCode; ?>" id="s_method_<?php echo $shipping_methodCode; ?>" checked="checked" class="radio validate-one-required-by-name hide"/>\
                                        <label for="s_method_<?php echo $shipping_methodCode; ?>"><?php echo $this->__($shipping_method_name); ?></label>\
                                        <span class="glyphicon glyphicon-ok  shippingSelectedIcon" id="<?php echo $shipping_methodCode; ?>_selected_icon"></span>\
                                        <span class="price"><?php echo Mage::app()->getStore()->formatPrice($shipping_method_price); ?></span>' +
            '</li>' +
            '</ul>' +
            '</dd>' +
            '</dl>';
        return shipping;
    }
    function getPaymentHtml() {
        var payment = '<div class="onestepcheckout-payment-methods">\
        <dl class="sp-methods" id="checkout-payment-method-load">\
                        <style type="text/css">\
                                #advice-validate-one-required-by-name-p_method_cashforpos{\
                                        display: none !important;\
                                }\
            </style>\
                        <dt code="cashforpos" class="payment_label  active">\
                                <span class="no-display"><input id="p_method_cashforpos" value="cashforpos" type="radio" name="payment[method]" title="<?php echo $this->__($cash_title); ?>" onclick="webpos_save_data(save_data_url,\'payment\');" checked="checked" class="radio validate-one-required-by-name"></span>\
                                <label for="p_method_cashforpos"><?php echo $this->__($cash_title); ?></label>\
                                <span class="glyphicon glyphicon-ok  paymentSelectedIcon" id="cashforpos_selected_icon"></span>\
            </dt>\
                </dl>\
        </div>';
        return payment;
    }

    function preparePendingOrdersHtml() {
        if($('cb_all')) $('cb_all').checked == false;
        if($('pending_orders_content') && getNumberPendingOrders() > 0){
            $('pending_orders_content').innerHTML = '';
            var pending_orders = getAllPendingOrders();
            for(var pendingKey in pending_orders){
                var orders = $('pending_orders_content').innerHTML;
                var pendingData = pending_orders[pendingKey];
                var viewData = pendingData.viewData;
                var customerInCart = pendingData.customerInCart;
                var cashin = viewData.cashin;
                var grandTotal = viewData.grandTotal;
                var email = (customerInCart != null)?customerInCart.email:' ';
                var pending_order_html = '\
			<tr class="pending_row" id="pending_row_'+pendingKey+'">\
				<td><input class="selected_order" type="checkbox" value="'+pendingKey+'"/></td>\
				<td><p class="customer_email">'+email+'</p></td>\
				<td><p class="grand_total">'+grandTotal+'</p></td>\
				<td><p class="cashin">'+cashin+'</p></td>';
                pending_order_html += '<td><span class="delete" onclick=\'deletePendingOrderAtPopup("'+pendingKey+'")\'><?php echo $this->__('Delete'); ?></span></td></tr>';
                orders += pending_order_html;
                $('pending_orders_content').innerHTML = orders;
            }
        }
    }

    function updateTaxTotals(tax_amount,direction){

		if(price_includes_tax == true) return;
		var rateByCustomer = getTaxRateByCustomer();
		var recalculated = false;
		var items = $$('#webpos_cart .product');
		if(items.length > 0){
			var subtotal = 0;
			items.each(function(el){
				var price = el.getAttribute('product_price');
				var qty = el.down('.img-product').down('.number').innerHTML;
				subtotal += parseFloat(qty) * parseFloat(price); 
			});
			tax_amount = subtotal * rateByCustomer / 100;
			recalculated = true;
		}
        if($('total_wp')){
            var oldTotal = $('total_wp').innerHTML;
            if($('webpos_cart_tax')){
				if(recalculated == false){
					var oldTaxTotal = getPriceFromString($('webpos_cart_tax').down('.price').innerHTML);
					var newTaxTotal = (direction == 'inc')?(oldTaxTotal + tax_amount):(oldTaxTotal - tax_amount);
                }else{
					newTaxTotal = tax_amount;
				}
                if(newTaxTotal < 0 ) newTaxTotal = 0;
                if(newTaxTotal == 0){
                    if($('offline_tax')) $('offline_tax').remove();
                }else $('webpos_cart_tax').down('.price').innerHTML = getPriceFormatedNoHtml(newTaxTotal);
            }else{
                if(tax_amount < 0 ) tax_amount = 0;
                var html = '\
				<div class="form-cart" id="offline_tax">\
					<div style="" class="el1 col-lg-8 col-md-8 col-sm-8 col-xs-8">\
						Tax    </div>\
					<div style="" class="el2 col-lg-4 col-md-4 col-sm-4 col-xs-4">\
						<div id="webpos_cart_tax" class="webpos_item_subtotal"><span class="price">'+getPriceFormatedNoHtml(tax_amount)+'</span></div>\
					</div>\
				</div>\
			';
                if(tax_amount == 0){
                    if($('offline_tax')) $('offline_tax').remove();
                }else $('total_wp').innerHTML = oldTotal + html;
            }
        }else{
            if($('offline_tax')) $('offline_tax').remove();
        }
    }

    function applyShippingPrice(){
        if($('total_wp')){
            if($('webpos_cart_shipping')){
            }else{
                var oldTotal = $('total_wp').innerHTML;
                var shipping_amount = getShippingPrice();
                if(shipping_amount < 0 ) shipping_amount = 0;
                var html = '\
				<div class="form-cart" id="offline_shipping">\
					<div style="" class="el1 col-lg-8 col-md-8 col-sm-8 col-xs-8">\
						<?php echo $this->__('Shipping & Handling ('.$shipping_carrier_name.' - '.$shipping_method_name.')'); ?>    </div>\
					<div style="" class="el2 col-lg-4 col-md-4 col-sm-4 col-xs-4">\
							<div id="webpos_cart_shipping" class="webpos_item_subtotal"><span class="price"><?php echo Mage::app()->getStore()->formatPrice($shipping_method_price); ?></span></div>\
					</div>\
				</div>\
			';
                $('total_wp').innerHTML = oldTotal + html;
                if(appliedShipping == false){
                    appliedShipping = true;
                    var oldSubtotals = getStringPriceFromString($('webpos_subtotal_button').down('.price').innerHTML);
                    oldSubtotals = parseFloat(convertPrice(oldSubtotals));
                    var newSubtotals = oldSubtotals + parseFloat(shipping_amount);
                    $('webpos_subtotal_button').innerHTML = getPriceFormatedHtml(parseFloat(newSubtotals));
                }
            }
        }
    }

</script>

<div id='pending_orders_popup'>
    <div id='pending_orders_loader'>
        <div class="img-ajax"></div>
    </div>
    <div class="pospanel">
        <div class="panel-heading"><h2 class="col-sm-9"><?php echo $this->__('Pending Orders'); ?></h2><button class="btn btn-save" onclick="savePendingOrders()"><?php echo $this->__('Save order(s)'); ?></button>
        </div>

        <div class="panel-body">
            <table class="table data order-tables table-responsive" cellspacing="0">
                <colgroup>
                    <col width="1">
                    <col width="1">
                    <col width="1">
                    <col width="1">
                    <col width="1">
                </colgroup><thead>
                <tr class="theadings">
                    <th><input onclick="selectAllPendingOrders(this)" id='cb_all' type="checkbox" value=""/></th>
                    <th><?php echo $this->__('Customer Email');?></th>
                    <th><?php echo $this->__('Grand total');?></th>
                    <th class="a-center"><?php echo $this->__('Cash in');?></th>
                    <th class="last"></th>
                </tr>
                </thead>
                <tbody class="even" id='pending_orders_content'>

                </tbody>
            </table>

        </div>
    </div>
</div>
<!--div id='pending_orders_content' class="hide">          
	<div class='payment_shipping'>
		<div class='shipping_method col-lg-6 col-md-6 col-sm-6 col-xs-6'>shipping_method</div>
		<div class='payment_method col-lg-6 col-md-6 col-sm-6 col-xs-6'>payment_method</div>
	</div>
	<div class='detail_data'>
		<div class="name-product col-lg-6 col-md-6 col-sm-6 col-xs-6">
			<div class='product_name'>abdfgt</div>
			<div class='product_options'>rwer,gfyfy</div>
		</div>
		<div class="product-qty col-lg-1 col-md-1 col-sm-1 col-xs-1">
			<?php echo '0' ?>
		</div>
		<div class="price col-lg-4 col-md-4 col-sm-4 col-xs-4">
			<span class='webpos_item_subtotal row_total'><?php echo '0' ?></span>
		</div>
		<div class='clear'></div>
	</div>
</div-->


<script type='text/javascript'>
if ($('webpos_overlay'))
    $('webpos_overlay').hide();
if ($('edit_cart_item_popup'))
    $('edit_cart_item_popup').hide();
if ($('webpos_dark_overlay'))
    $('webpos_dark_overlay').hide();
if ($('pending_orders_popup'))
    $('pending_orders_popup').hide();

/* Vietdq custom price*/
var currencySymbol = "<?php echo Mage::helper('webpos')->getCurrencySymbol(); ?>";
function checkQty(event) {
    var keyValue = String.fromCharCode(event.which);
    var keyCode = event.which || event.keyCode;
    if (keyCode != 8) {
        if (keyCode < 48 || keyCode > 57) {
            event.preventDefault();
        }
    }

}
function keyCheckCustomPrice(event)
{
    var KeyID = event.keyCode;

    switch (KeyID)
    {
        case 8:
            $('clear-number').click();
            break;
        default:
            break;
    }
}

var groupSymbolNumber;
var decimalSymbolNumber;
decimalSymbolNumber = priceFormat.decimalSymbol;
groupSymbolNumber = priceFormat.groupSymbol;
function numberWithCommas(price) {
    price = price.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
    return price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
function formatNumberWithDotCommas(price) {
    var parts = price.toString().split(".");
    return parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, groupSymbolNumber) + (parts[1] ? decimalSymbolNumber + parts[1] : "");
}
var countDiscountAmount = 0;
var hisDiscountAmount = [""];
function formatInputPriceCustomPrice(event) {
    var keyValue = String.fromCharCode(event.which);
    var keyCode = event.which || event.keyCode;
    $$('.custom_price_tab .btn-default').each(function (element) {
        if (element.value == keyValue)
            element.click();
    });
}
$$('.custom_price_tab .btn-default').each(function (element) {
    element.observe("click", function (event) {
        $('edit_cart_item_popup').setAttribute('has_change', 'yes');
        var productObject = getProductObject();
        if (element.id != 'clear-number') {
            var elementValue = element.value;
            /* can not apply discount > 100% */
            if ($D('#btn-percent').hasClass('btn2')) {
                if (parseInt(hisDiscountAmount[countDiscountAmount]) / 100 > 10 || (parseInt(hisDiscountAmount[countDiscountAmount]) / 100 == 10 && element.value > 0) || ((parseInt(hisDiscountAmount[countDiscountAmount]) / 100 > 1 && element.value == '00'))) {
                    elementValue = '';
                }
            }
            if (elementValue != '') {
                if (productObject.attr('product_price') != '' && convertLongNumber(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 100))
                    > productObject.attr('product_price') && getEditPriceType() == 'discount') {

                } else {
                    countDiscountAmount++;
                    hisDiscountAmount[countDiscountAmount] = hisDiscountAmount[countDiscountAmount - 1] + elementValue;
                }
            }
            /**/
        }
        else {
            if (hisDiscountAmount[hisDiscountAmount.length - 1] / hisDiscountAmount[hisDiscountAmount.length - 2] == '100') {
                hisDiscountAmount[countDiscountAmount] = hisDiscountAmount[countDiscountAmount] / 10;
            }
            else {
                if (hisDiscountAmount.length > 1)
                    hisDiscountAmount.pop();
                if (countDiscountAmount >= 1)
                    countDiscountAmount--;
            }
        }
        if (typeof hisDiscountAmount[countDiscountAmount] != "undefined") {
            if ($D('#btn-percent').hasClass('btn2'))
                var symbol = '%';
            else
                var symbol = "<?php echo Mage::helper('webpos')->getCurrencySymbol(); ?>";
            if (!hisDiscountAmount[countDiscountAmount])
                hisDiscountAmount[countDiscountAmount] = 0;
            if (hisDiscountAmount[countDiscountAmount] != 0) {
                if (symbol == '%') {
					// Changed By Tuan bun (27/08/2015): custom price
					if(priceFormat.precision==0)
						$('discount-amount').value = getStringPriceFromString(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]))) + symbol;
					else if(priceFormat.precision==1)
						$('discount-amount').value = getStringPriceFromString(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 10)) + symbol;
					else if(priceFormat.precision==2)
						$('discount-amount').value = getStringPriceFromString(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 100)) + symbol;
					// Changed By Tuan bun (27/08/2015): custom price
                    $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
                } else {
					// Changed By Tuan bun (27/08/2015): custom price
					var price_custom = '';
					if(priceFormat.precision==0)
						price_custom = convertLongNumber(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount])))
					else if(priceFormat.precision==1)
						price_custom = convertLongNumber(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 10))
					else if(priceFormat.precision==2)
						price_custom = convertLongNumber(getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 100))
					// Changed By Tuan bun (27/08/2015): custom price
					
                    if (productObject.attr('product_price') != '' && price_custom
                        > productObject.attr('product_price') && getEditPriceType() == 'discount') {
                        $('discount-amount').value = getPriceFormatedNoHtml(productObject.attr('product_price'));
                        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);


                    } else {
						// Changed By Tuan bun (27/08/2015): custom price
						if(priceFormat.precision==0)
							$('discount-amount').value = getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]));
						else if(priceFormat.precision==1)
							$('discount-amount').value = getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 10);
						else if(priceFormat.precision==2)
							$('discount-amount').value = getPriceFormatedNoHtml(parseInt(hisDiscountAmount[countDiscountAmount]) / 100);
					// Changed By Tuan bun (27/08/2015): custom price
                        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
                    }
                }
            }
            else {
                $('discount-amount').value = '';
                $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
            }
        }
    });
});
var resetPopup = function () {
    hideCustomPriceTab();
    $D('#discount-amount').val('');
    $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html("<?php echo Mage::helper('core')->currency(0, true, false); ?>");
    if ($D('#btn-custom').hasClass('choose')) {
        $D('#btn-custom').removeClass('choose');
        $D('#btn-custom').addClass('nochoose');
        $D('#btn-discount').removeClass('nochoose');
        $D('#btn-discount').addClass('choose');

    }
    $D('.label-type').each(function () {
        $D(this).html('Discount');
    });
    hisDiscountAmount = [""];
    countDiscountAmount = 0;
};
$D('#discount-amount').change(function () {
    var discountValue = $D('#discount-amount').val();
    $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html(discountValue);
    $('edit_cart_item_popup').setAttribute('has_change', 'yes');
});

function hasClassName(ele, cls) {
    return !!ele.className.match(new RegExp('(\\s|^)' + cls + '(\\s|$)'));
}
function addClassName(ele, cls) {
    if (!hasClassName(ele, cls))
        ele.className += " " + cls;
}

function removeClassName(ele, cls) {
    if (hasClassName(ele, cls)) {
        var reg = new RegExp('(\\s|^)' + cls + '(\\s|$)');
        ele.className = ele.className.replace(reg, ' ');
    }
}
function focusFunction(classElement) {
    classElement.each(function (element) {
        element.observe("click", function (event) {

            if (element.id == 'btn-dollor') {
                $D('#btn-percent').removeClass('btn2');
                $D('#btn-percent').addClass('btn1');
                $D('#discount-amount').val('');
                hisDiscountAmount = [""];
                countDiscountAmount = 0;
                $D('#discount-amount').attr('placeholder', "<?php echo Mage::helper('core')->currency(0, true, false); ?>");
                $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html("<?php echo Mage::helper('core')->currency(0, true, false); ?>");
                //vvv
            }
            if (element.id == 'btn-percent') {
                $D('#btn-dollor').removeClass('btn2');
                $D('#btn-dollor').addClass('btn1');
                $D('#discount-amount').val('');
                hisDiscountAmount = [""];
                countDiscountAmount = 0;
                $D('#discount-amount').attr('placeholder', '0.00%');
                $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html("0.00%");
            }

        });
    });
}
focusFunction($$('.btn1'));
focusFunction($$('.btn2'));
var switchEditType = function () {
    if ($D('#btn-custom').hasClass('choose')) {
        $D('#btn-custom').removeClass('choose');
        $D('#btn-custom').addClass('nochoose');
        $D('#btn-discount').removeClass('nochoose');
        $D('#btn-discount').addClass('choose');
        $D('.label-type').each(function () {
            $D(this).html('Discount');
        });
        doSwapCustomDiscount();
        hisDiscountAmount = [""];
        countDiscountAmount = 0;

    } else {
        $D('#btn-custom').removeClass('nochoose');
        $D('#btn-custom').addClass('choose');
        $D('#btn-discount').removeClass('choose');
        $D('#btn-discount').addClass('nochoose');
        $D('.label-type').each(function () {
            $D(this).html('Custom Price');
        });
        doSwapCustomDiscount();
        hisDiscountAmount = [""];
        countDiscountAmount = 0;
    }
};
$D('#btn-custom').click(function () {
    if ($D('#btn-custom').hasClass('nochoose'))
        switchEditType();
    showCustomPriceTab();
//        $D('#discount-amount').val(formatCurrency(swapCustomDiscountDollar(), priceFormat));
//        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
});
$D('#btn-discount').click(function () {
    if ($D('#btn-discount').hasClass('nochoose'))
        switchEditType();
    showCustomPriceTab();
//        $D('#discount-amount').val(formatCurrency(swapCustomDiscountDollar(), priceFormat));
//        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
});
$D('#btn-custom').dblclick(function () {
    if ($D('#btn-custom').hasClass('nochoose'))
        switchEditType();
    showCustomPriceTab();
//        $D('#discount-amount').val(formatCurrency(swapCustomDiscountDollar(), priceFormat));
//        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
});
$D('#btn-discount').dblclick(function () {
    if ($D('#btn-discount').hasClass('nochoose'))
        switchEditType();
    showCustomPriceTab();
//        $D('#discount-amount').val(formatCurrency(swapCustomDiscountDollar(), priceFormat));
//        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
});



var getProductObject = function () {
    var productId = $('edit_cart_item_popup').getAttribute('prdid');
    var itemId = $('edit_cart_item_popup').getAttribute('itemid');
    var productObjectById = $D('.product[prdid=' + productId + ']');

    //25/7/2015
    if ($D('.product[prdid=' + productId + ']').length >= 2) {
        $D('.product[prdid=' + productId + ']').each(function () {
            if ($D('#edit_cart_item_popup').attr('cart_item') == $D(this).attr('id')) {
                productObjectById = $D(this);
            }
        });


    }
    var productObjectByItem = $D('.product[itemid=' + itemId + ']');
    var productObject;
    if (itemId == "undefined") {
        productObject = productObjectById;
    } else {
        productObject = productObjectByItem;
    }
    return productObject;

};


var currentProductPrice = function () {
    var productObject = getProductObject();
    var price = productObject.attr('product_price');
    price = parseFloat(price);
    return price;
};


var handleIncreaseButton = function () {
    var oldValue = $D('#editpopup_product_qty').val();
    $D('#editpopup_product_qty').val(parseInt(oldValue) + 1);
    //tang qty

    var productObject = getProductObject();
    var currency = '<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>';
    var oldQty = parseFloat(productObject.find(".number").html());
    var newQty = oldQty + 1;
    productObject.find(".number").html(newQty); //tang so chu thich
    productObject.attr('qty', newQty);
    var curQty;
    curQty = productObject.find(".number").html();
    curQty = parseFloat(curQty);
    if (curQty == 1) {
        if (productObject.find(".number").hasClass('hide') == false) {
            productObject.find(".number").addClass('hide')
        }

    } else
    {
        if (productObject.find(".number").hasClass('hide')) {
            productObject.find(".number").removeClass('hide');
        }
    }
    if (curQty == 0) {   //xoa bang js
        if (productObject.hasClass('hide') == false) {
            productObject.addClass('hide');
        }
    } else {
        if (productObject.hasClass('hide') == true) {
            productObject.removeClass('hide');
        }
    }
    calculatePriceJS();
    $('edit_cart_item_popup').setAttribute('has_change', 'yes');
};

var handleDescreaseButton = function () {
    var oldValue = $D('#editpopup_product_qty').val();
    if (parseInt(oldValue) >= 1) {
        $D('#editpopup_product_qty').val(parseInt(oldValue) - 1);
    }


    //giam qty
    var productObject = getProductObject();
    var currency = '<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>';
    var oldQty = parseFloat(productObject.find(".number").html());
    var newQty = oldQty;
    if (oldQty >= 1) {
        newQty = oldQty - 1;
    }
    productObject.find(".number").html(newQty); //tang so chu thich
    productObject.attr('qty', newQty);
    var curQty;
    curQty = productObject.find(".number").html();
    curQty = parseFloat(curQty);

    if (curQty <= 1) {
        if (productObject.find(".number").hasClass('hide') == false) {
            productObject.find(".number").addClass('hide')
        }

    } else
    {
        if (productObject.find(".number").hasClass('hide')) {
            productObject.find(".number").removeClass('hide');
        }
    }
    if (curQty == 0) {   //xoa bang js
        if (productObject.hasClass('hide') == false) {
            productObject.addClass('hide');
        }
    } else {
        if (productObject.hasClass('hide') == true) {
            productObject.removeClass('hide');
        }
    }
    calculatePriceJS();
    $('edit_cart_item_popup').setAttribute('has_change', 'yes');
};

$D("#bt_inc_qty").click(function () {
    handleIncreaseButton();
    collectTotalJS();
    collectGrandTotalJS();
    collectCartTotal();
});
$D("#bt_desc_qty").click(function () {
    handleDescreaseButton();
    collectTotalJS();
    collectGrandTotalJS();
    collectCartTotal();

});

var getChangeType = function () {
    var changeType;
    if ($D('#btn-percent').hasClass('btn2')) {
        changeType = 'percent';
    } else {
        changeType = 'dollar';
    }
    return changeType;

};

var applyDiscount = function () {
    var currency = '<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>';
    var changeType;
    changeType = getChangeType();


    var productId = $('edit_cart_item_popup').getAttribute('prdid');
    var itemId = $('edit_cart_item_popup').getAttribute('itemid');
    var productPrice = $('edit_cart_item_popup').getAttribute('product_price');
    var customAmount;
    if (customAmount != '')
        customAmount = parseFloat(reFormatPrice());
    else
        customAmount = '';
    var productObject;
    productObject = getProductObject();
    var qty = parseFloat($D('#editpopup_product_qty').val());
    var editPriceType;
    editPriceType = getEditPriceType();
    //edit price by js
    var price = calculateCustomPrice(editPriceType, changeType, productPrice, customAmount);
    var newPrice = price * qty;
    newPrice = newPrice.toFixed(2);
    if ($D('#discount-amount').val() == '') {
        $D('#discount-amount').val('0');

        customAmount = 0;
        price = 0;
    }
    calculatePriceJS();

    if (qty == 0) {
        productObject.remove();
    }
    collectTotalJS();
    collectGrandTotalJS();
    var hasChange = 'no';
    if (productObject.attr('custom_price') >= 0 && isNaN(customAmount) == false) {
        hasChange = 'yes';
    }
    var resetPrice = 'no';
    if ($D('#discount-amount').val() == '' && productObject.attr('custom_price') == '') {
        resetPrice = 'yes';
    }

    resetPopup();
    if (itemId != 'undefined') {
        showColrightAjaxloader();
        $D.ajax({
            url: '<?php echo $this->getUrl('webpos/product/editPrice',array('_forced_secure' => $this->getRequest()->isSecure())); ?>',
            method: 'POST',
            dataType: 'json',
            data: {
                productId: productId,
                customPrice: customAmount,
                changeType: changeType,
                itemId: itemId,
                editPriceType: editPriceType,
                priceEdit: price,
                qty: qty,
                hasChange: hasChange,
                resetPrice: resetPrice
            },
            success: function (response) {
                hideColrightAjaxloader();
                if (response.message) {

                    showToastMessage('danger', 'Error', response.message);
                    emptyCart(empty_cart_url);
                } else {
                    $D('#webpos_cart_custom_sale').addClass('hide');
                    if (response.grandTotal) {
                        $('cashin_fullamount').innerHTML = response.grandTotal;
                        if ($('remain_value_label'))
                            $('remain_value_label').innerHTML = response.grandTotal;
                        if ($('remain_value'))
                            $('remain_value').innerHTML = response.grandTotal;
                    }
                    if (response.downgrandtotal)
                        $('round_down_cashin').innerHTML = response.downgrandtotal;
                    if (response.upgrandtotal)
                        $('round_up_cashin').innerHTML = response.upgrandtotal;
                    if (response.grand_total)
                        $('webpos_subtotal_button').innerHTML = response.grand_total;
                    if (response.payment_method && $('payment_method'))
                        $('payment_method').update(response.payment_method);
                    if (response.shipping_method && $('shipping_method'))
                        $('shipping_method').update(response.shipping_method);
                    if (response.pos_items && $('webpos_cart'))
                        $('webpos_cart').update(response.pos_items);
                    if (response.totals && $('pos_totals'))
                        $('pos_totals').update(response.totals);
                    if (response.number_item && $('total_number_item'))
                        $('total_number_item').update(response.number_item);
                    if (response.errorMessage && response.errorMessage != '') {
                        showToastMessage('danger', 'Error', response.errorMessage);
                    }
                }

            }
        });
    }
};
$D('#change-price').click(function () {
    if ($('webpos_overlay'))
        $('webpos_overlay').hide();
    if ($('edit_cart_item_popup'))
        $('edit_cart_item_popup').hide();
    var productObject;
    productObject = getProductObject();
    productObject.removeClass('active');
    saveCart(function(){webpos_save_data(save_data_url,'payment', function(){applyDiscount()})}); 
    //resetPopup();
});
//$D('#discount-amount').change(function() {
//	  var discountAmount = parseFloat($D('#discount-amount').val());
//	  $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html(discountAmount);
//});

$D('#editpopup_product_qty').blur(function () {
    var productObject = getProductObject();
    var oldQty = parseFloat(productObject.find(".number").html());
    var newQty = parseFloat($D('#editpopup_product_qty').val());
    if ($D('#editpopup_product_qty').val() == '') {
        $D('#editpopup_product_qty').val(1);
        productObject.find(".number").html(1);
    }
    productObject.find(".number").html(newQty);
    if (newQty != oldQty) {
        $('edit_cart_item_popup').setAttribute('has_change', 'yes');
    }
    calculatePriceJS();
});
/* end Vietdq custom price*/
var swapCustomDiscountDollar = function () {
    var result;
    var amount = convertLongNumber(getStringPriceFromString($('discount-amount').value));
    var productObject = getProductObject();
    var productPrice;

    if (productObject.attr('product_price') != '') {
        productPrice = productObject.attr('product_price');
        if (amount <= productPrice) {
            result = productPrice - amount;
            return result;
        } else
            return 0;
    }

    return 0;
};

var swapCustomDiscountPercent = function (amount) {
    var result;
    var amount = parseFloat(convertLongNumber($('discount-amount').value.replace('%', '')));
    if (amount <= 100) {
        result = 100 - amount;
    } else {
        result = 0;
    }
    result = formatCurrency(result, priceFormat);
    result = getStringPriceFromString(result);
    return result;
};

var doSwapCustomDiscount = function () {
    if ($D('#btn-dollor').hasClass('btn2')) {
        $D('#discount-amount').val(formatCurrency(swapCustomDiscountDollar(), priceFormat));
        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
    } else {
        $D('#discount-amount').val((swapCustomDiscountPercent()) + '%');
        $D('#edit_cart_item_popup').find('.webpos_item_subtotal').html($('discount-amount').value);
    }
};

</script>
</div>