<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;" colspan="3"><h3 class="icon-head head-customer"><?php echo Mage::helper('catalog')->__('Customer Types') ?></h3></td>
<!--        <td class="form-buttons">
            <button type="button" title="Add a type" class="scalable add" onclick="location.href='<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/customer/new"); ?>'">
                <span>Add a type</span>
            </button>
        </td>-->
    </tr>
</table>
</div>