<div class="report_box entry-edit">
    <fieldset>
        <h2 class="mbl"><?php echo $this->getTitle(); ?></h2>
        <textarea id="customer_notes_edit" rows="4" cols="150" placeholder="Enter your notes">
<?php if (strlen(trim($this->getCustomerNotes())) > 0) {
                echo $this->getCustomerNotes();
            }
            ?></textarea>
        <br>
        <button class="scalable edit" style="float: right; margin-top: 10px;" onclick="updateNotes();">
            <span>Save</span>
        </button>
    </fieldset>
</div>
<script>
    function updateNotes() {
        Element.show('loading-mask');
        customerId = <?php echo $this->getCustomerId(); ?>;
        customerNotes = $('customer_notes_edit').value;
        var parameters = {customerId: customerId, customerNotes: customerNotes};
        var url = '<?php echo Mage::helper('adminhtml')->getUrl('inventorycustomeradmin/adminhtml_customertypes/editnotes') ?>';
        var request = new Ajax.Request(url, {
            method: 'post',
            parameters: parameters,
            onFailure: '',
            onSuccess: function (transport) {
                if (transport.status == 200) {
                    var result = transport.responseText.evalJSON();
                    if (result.success == 1) {
                        alert('Successful Edit');
                        window.close()
                    } else {
                        alert('Failed! Try again');
                    }
                    Element.hide('loading-mask');
                }
            }
        });
    }
</script>