
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php
$storeId = Mage::app()->getStore()->getId(); // return current store id //echo Mage::app()->getRequest()->getParam('order');exit;
$list_check_String=Mage::getStoreConfig('catalog/frontend/list_per_page_values',$storeId);
$list_array = explode(",",$list_check_String);
$flag_list_status = in_array($_GET['limit'],$list_array);
$mode = $this->getLayout()->createBlock('catalog/product_list_toolbar')->setChild('product_list_toolbar_pager', $pager)->getCurrentMode();
?>
<?php $config1 = Mage::getStoreConfig('web/default/cms_home_page'); ?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <?php if( $this->isEnabledViewSwitcher() ): ?>

      <?php if(($config1=='fabia_home_eight')||($config1=='fabia_home_five')) { ?> <!-- For version 8 and 5-->

        <div class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>           
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <span title="<?php echo $_label ?>" class="button button-active button-<?php echo strtolower($_code); ?> first"><?php echo $_label ?></span>&nbsp;
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="button-<?php echo strtolower($_code); ?> last"><?php echo $_label ?></a>&nbsp;
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>          
        </div>

      <?php } else { ?>  <!-- For rest version  -->

        <div class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>           
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <span title="<?php echo $_label ?>" class="button button-active button-<?php echo strtolower($_code); ?> first"></span>&nbsp;
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="button-<?php echo strtolower($_code); ?> last"></a>&nbsp;
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>          
        </div>

      <?php } ?> <!-- End For rest version  -->

        <?php endif; ?>
    

    </div> <!--sorter-->
    <?php endif; ?>
           <div id="sort-by">
         <ul>
          <label class="left"><?php echo $this->__('Sort By:') ?></label>
            <li>
                <a href="#"> 
                  <?php if(Mage::app()->getRequest()->getParam('order')=="") { ?>
                  <?php echo Mage::getStoreConfig('catalog/frontend/default_sort_by'); } else {?>
                  <?php echo Mage::app()->getRequest()->getParam('order');} ?> 
                  <span class="right-arrow"></span> 
                </a>           
          <ul>
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>               
              <li>
                <a href="<?php echo $this->getOrderUrl($_key, 'asc') ?>">
                    <?php echo $this->__($_order) ?>
                </a>
              </li>
            <?php endforeach; ?>
          </ul> 
        </li>          
      </ul>
        <?php if($this->getCurrentDirection() == 'desc'): ?>
             <a class="button-asc left" href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">
              <?php if(($config1=='fabia_home_five')){?>
              <span class="glyphicon glyphicon-arrow-up" style="color:#999;font-size:11px;"></span>
              <?php }else{?>
              <span class="top_arrow"></span></a>
              <?php } ?>
        <?php else: ?>
             <a class="button-desc left" href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">

              <?php if(($config1=='fabia_home_five')){?>
              <span class="glyphicon glyphicon-arrow-down" style="color:#999;font-size:11px;"></span>
              <?php }else{?>
              <span class="top_arrow"></span></a>
              <?php } ?>

        <?php endif; ?>
    </div> <!--sort-by--> 

    <div class="pager"> 
    
<!-- BEGIN LIMITER -->
    <div id="limiter">
     <ul>
      <label><?php echo $this->__('View: ') ?></label>
       <li>
          <a href="#"> 
             <?php if((Mage::app()->getRequest()->getParam('mode')=='grid')&&(Mage::app()->getRequest()->getParam('limit')=="")){?>
                <?php echo Mage::getStoreConfig('catalog/frontend/grid_per_page');}?>

             <?php if((Mage::app()->getRequest()->getParam('mode')=='list')&&(Mage::app()->getRequest()->getParam('limit')=="")){?>
                <?php echo Mage::getStoreConfig('catalog/frontend/list_per_page');}?>
    
             <?php if((Mage::app()->getRequest()->getParam('mode')=='grid')&&(Mage::app()->getRequest()->getParam('limit')!="")){
                 if(!$flag_list_status){
                    echo Mage::getStoreConfig('catalog/frontend/grid_per_page');
                 } else { 
                    echo Mage::app()->getRequest()->getParam('limit');}}
             ?>

             <?php if((Mage::app()->getRequest()->getParam('mode')=='list')&&(Mage::app()->getRequest()->getParam('limit')!="")){
                 if(!$flag_list_status){
                    echo Mage::getStoreConfig('catalog/frontend/list_per_page');
                 } else { 
                    echo Mage::app()->getRequest()->getParam('limit');}}
            ?>
    
            <?php  if((Mage::app()->getRequest()->getParam('mode')=="")&&(Mage::app()->getRequest()->getParam('limit')=="")){ 
                  if($mode == 'grid'){
                    echo Mage::getStoreConfig('catalog/frontend/grid_per_page');
                 } else { 
                    echo Mage::getStoreConfig('catalog/frontend/list_per_page');
                }
           }?>
    
            <?php if((Mage::app()->getRequest()->getParam('mode')=="")&&(Mage::app()->getRequest()->getParam('limit')!="")){
               echo Mage::app()->getRequest()->getParam('limit');
             } 
            ?>
            <span class="right-arrow"></span>
        </a>
        <ul>           
          <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>                
            <li>
              <a href="<?php echo $this->getLimitUrl($_key) ?>">
                 <?php echo $_limit ?>
              </a>
            </li>
          <?php endforeach; ?>           
        </ul> 

        </li>
      </ul>
    </div>  <!--limiter-->
    <?php echo $this->getPagerHtml() ?> 
  </div> <!--pager-->
       
</div> <!--toolbar-->
<?php endif ?>
