
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>

    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>
    <?php //$currentCategory = Mage::registry('current_category') ?>

<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>

  <li><div class="home"> <a href="<?php echo $this->getUrl('') ?>"><i class="icon-home"></i><?php echo $this->__('Home'); ?></a> </div></li>
              
  <?php echo $_menu; ?>
      

<?php endif ?>