<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>

    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>

<?php if (count($_categories) > 0): ?>

  <div class="menu-trigger">
     <a href="#"><div class="menu icon"> <span></span> <span></span> <span></span> <span></span> </div>
      </a> 
  </div>

 <div class="menu-dropdown">
  <ul class="mobile-menu">
    <?php if (Mage::getStoreConfig('fabiasettings/fabiasettings_header/navigation_home')): ?>
      <li>
          <a href="<?php echo $this->getUrl('') ?>"><?php echo $this->__('Home'); ?><span>+</span></a>
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home7_tab_dropdown_block')->toHtml(); ?>
      </li>
    <?php endif; ?><!-- End if home -->
    <?php foreach($_categories as $_category): ?>
        <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
        <?php $_subcategories = $_category->getChildrenCategories() ?>
    <li>
       <a href="<?php echo $_helper->getCategoryUrl($_category) ?>"><?php echo $_category->getName() ?><?php if (count($_subcategories) > 0): ?><span>+</span><?php endif ?></a>
       <ul class="submenu">
          <?php if (count($_subcategories) > 0): ?>
             <?php foreach($_subcategories as $_subcategory): ?>
                <?php $_subcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>                             
                <?php $_subsubcategories = $_subcategory->getChildrenCategories() ?>
                <li>
                  <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>"><?php echo $_subcategory->getName() ?><?php if (count($_subsubcategories) > 0): ?><span>+</span><?php endif ?></a>
                  <ul class="submenu">
                    <?php if (count($_subsubcategories) > 0): ?>
                      <?php foreach($_subsubcategories as $_subsubcategory): ?>
                          <?php $_subsubsubcategory = Mage::getModel('catalog/category')->load($_subsubcategory->getId()) ?>                             
                          <?php $_subsubsubcategories = $_subsubcategory->getChildrenCategories() ?>
                          <li>
                             <a href="<?php echo $_helper->getCategoryUrl($_subsubsubcategory) ?>"><?php echo $_subsubsubcategory->getName() ?><?php if (count($_subsubsubcategories) > 0): ?><span>+</span><?php endif ?></a>
                             <ul class="submenu">
                               <?php if (count($_subsubsubcategories) > 0): ?>
                                <?php foreach($_subsubsubcategories as $_subsubsubcategory): ?>
                                   <?php $_subsubsubsubcategory = Mage::getModel('catalog/category')->load($_subsubsubcategory->getId()) ?>                             
                                   <?php $_subsubsubsubcategories = $_subsubsubcategory->getChildrenCategories() ?>
                                  <li>
                                     <a href="<?php echo $_helper->getCategoryUrl($_subsubsubsubcategory) ?>"><?php echo $_subsubsubsubcategory->getName() ?></a>
                                  </li> <!--End fourth li-->
                                <?php endforeach; ?> <!-- End foreach($_subsubsubcategories as $_subsubsubcategory) -->
                               <?php endif ?> <!-- End if (count($_subsubsubcategories) > 0) -->
                              </ul><!--submenu-->
                          </li> <!--End third li-->
                      <?php endforeach; ?> <!-- End foreach($_subsubcategories as $_subsubcategory) -->
                    <?php endif ?> <!-- End if (count($_subsubcategories) > 0) -->
                  </ul><!--submenu-->
                </li> <!--End second li-->
             <?php endforeach; ?> <!-- End foreach($_subcategories as $_subcategory) -->
          <?php endif ?> <!-- End if (count($_subcategories) > 0) -->
       </ul> <!--submenu-->
    </li> <!-- End first li -->
    <?php endforeach; ?> <!-- End foreach($_categories as $_category) -->     
  </ul> <!--navmenu-->
</div> <!--menu-dropdown-->
<?php endif ?> <!-- End if (count($_categories) > 0) -->

