<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>

    
<?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>
    <?php $menu_type = Mage::getStoreConfig('fabiasettings/fabiasettings_menu/navigation_menu_type'); ?>
    <?php $config1 = Mage::getStoreConfig('web/default/cms_home_page'); ?>

    <?php if (count($_categories) > 0): ?>
             <!-- BEGIN NAV -->  
            <ul id="nav">
                  <?php if (Mage::getStoreConfig('fabiasettings/fabiasettings_header/navigation_home')): ?>
                <li id="nav-home" class="level0 parent drop-menu"><a class="level-top" href="<?php echo $this->getUrl('') ?>"><span><?php echo $this->__('Home'); ?></span></a>
                  
                  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home_tab_dropdown_block')->toHtml(); ?>
                  
                  </li>
              <?php endif; ?>
            <?php foreach($_categories as $_category): ?>
                                           
             
                    <?php if($menu_type == 'mega-menu') { ?>                   
                         <li class="level0 nav-5 level-top">  
                     <?php } else { ?>
                         <li class="level0 nav-5 level-top drop-menu">  
                     <?php } ?>       
             
                  

<?php if($this->getCurrentCategory()->getId()==$_category->getId()) { ?>
                    <a class="level-top active" href="<?php echo $_helper->getCategoryUrl($_category) ?>"><span><?php echo $_category->getName() ?></span></a>
<?php } else { ?> 
                    <a class="level-top" href="<?php echo $_helper->getCategoryUrl($_category) ?>"><span><?php echo $_category->getName() ?></span></a>
<?php } ?>       
                    <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                    <?php $_subcategories = $_category->getChildrenCategories() ?>
                    <?php if (count($_subcategories) > 0): ?>

<?php if($menu_type == 'mega-menu') { ?>
                        <div class="level0-wrapper dropdown-6col" style="left: 0px; display: none;">
                          <div class="level0-wrapper2">

                            <?php echo $_category->getData('fabia_custom_cat_link') ?>

                            

<?php if($_category->getData('fabia_menu_type') == "rightimage") { ?>
  <div class="nav-block nav-block-center grid13-8 itemgrid itemgrid-4col"> 
<?php } elseif($_category->getData('fabia_category_product_id') != '') { ?> <!-- if product img left side -->
  <div class="nav-block nav-block-center grid12-8 itemgrid itemgrid-4col">
<?php } else { ?>
  <div class="nav-block nav-block-center">
<?php } ?>
               
<?php } ?>  <!--mega menu-->       

<?php if($menu_type == 'mega-menu') { ?>                            
                                <ul class="level0">
<?php } else { ?>
                                <ul style="display: none;" class="level1">
<?php } ?>
                        
                         <?php foreach($_subcategories as $_subcategory):
$_secondLevelCat = Mage::getModel('catalog/category')->load($_subcategory->getId());
                                if (!$_secondLevelCat->getData("include_in_menu")) continue;
 ?>
                                <?php $_subcategory = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>                             
                                <?php $_subsubcategories = $_subcategory->getChildrenCategories() ?>
                            <li class="level1 nav-6-1 parent item">

                        <?php if($menu_type == 'mega-menu') { ?> 
                            <?php if($_subcategory->getThumbnail()) { ?>
                               <div class="cat-img"><img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.$_subcategory->getThumbnail()  ?>" alt="<?php echo $_subcategory->getName() ?>" /></div>
                            <?php } ?>
                        <?php } ?>
                              
                                <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>"><span><?php echo $_subcategory->getName() ?></span></a>
                                <!--sub sub category-->
                               
                                <?php if (count($_subsubcategories) > 0): ?>
                                 
                                   <ul class="level1">
                                    <?php foreach($_subsubcategories as $_subsubcategory): 
$_thirdLevelCat = Mage::getModel('catalog/category')->load($_subsubcategory->getId());
                                          if (!$_thirdLevelCat->getData("include_in_menu")) continue;

?>
                                       <li class="level2 nav-6-1-1">
                                          <a href="<?php echo $_helper->getCategoryUrl($_subsubcategory) ?>"><span><?php echo $_subsubcategory->getName() ?></span></a>
            
                                          <?php $_subsubsubcategory = Mage::getModel('catalog/category')->load($_subsubcategory->getId()) ?>                             
                                          <?php $_subsubsubcategories = $_subsubcategory->getChildrenCategories() ?>
                                          <?php if (count($_subsubsubcategories) > 0): ?>
                                             <div class="level2 sub-wrapper" style="height: auto;">
                                                   <ul class="level2">
                                                     <?php foreach($_subsubsubcategories as $_subsubsubcategory): ?>
                                                       <li class="level3 nav-1-1-1-1">
                                                         <a href="<?php echo $_helper->getCategoryUrl($_subsubsubcategory) ?>"><span><?php echo $_subsubsubcategory->getName() ?></span></a>
                                                       </li> <!--level3 nav-1-1-1-1-->
                                                     <?php endforeach; ?>
                                                   </ul> <!--level2-->
                                             </div> <!--level2 sub-wrapper-->
                                          <?php endif; ?>

                                       </li> <!--level2 nav-6-1-1-->
                                    <?php endforeach; ?>
                                   </ul> <!--level1-->
                                  
                               <?php endif; ?>
                                 <!--sub sub category-->  
                                                                                        
                            </li> <!--level1 nav-6-1 parent item-->
                         <?php endforeach; ?>        
                                </ul> <!--level0-->

<?php if($menu_type == 'mega-menu') { ?>

<?php if($_category->getData('fabia_menu_type') == "rightimage") { ?>
      <?php echo $_category->getData('fabia_custom_cat_desc') ?>
<?php } ?>

                
                              
                            </div> <!--nav-block nav-block-center-->  

<?php if($_category->getData('fabia_menu_type') == "rightimage") { ?>
  <div class="nav-block nav-block-right std grid12-4">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_top_menu_left_position_static_block')->toHtml(); ?>
  </div> <!--nav-block nav-block-right std grid12-4-->
<?php } ?>


<?php $prodid = $_category->getData('fabia_category_product_id') ?>
     
     <?php if($prodid != '') { 
             //echo ">>";
        echo $this->getLayout()->createBlock('catalog/product')->setData('fabia_category_product_id',$prodid)->setTemplate('catalog/product/top-menu-category.phtml')->toHtml(); 

      }?>                     


<?php if($_category->getData('fabia_menu_type') != "rightimage") { ?>
      <?php echo $_category->getData('fabia_custom_cat_desc') ?>
<?php } ?>
                                                                                                             
                          </div> <!--level0-wrapper2-->
			<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('category-node-'.$_category->getId())->toHtml(); ?>
                       </div> <!--level0-wrapper dropdown-6col-->

<?php } ?>  <!--mega menu-->

                    <?php endif; ?>
                    </li> 
             <?php endforeach; ?> 
<!-- custom block -->
            <?php  $custom_tab = Mage::getModel('cms/block')->load('fabia_navigation5_block');
            if($custom_tab->getIsActive()) {
            echo '
            <li class="nav-custom-link level0 level-top parent">
                <a href="#" class="level-top">
                    <span>'.$custom_tab->getTitle().'</span>
                </a>
                <div class="level0-wrapper custom-menu" style="left: 0px; display: none;">'.$this->getLayout()->createBlock('cms/block')->setBlockId('fabia_navigation5_block')->toHtml().'</div>
            </li>';
          }  ?>
            </ul> <!--nav-->

    <?php endif; ?>



 
