<?php
/**
 * Email Template Manager
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitemails
 * @version      2.0.15
 * @license:     GJkOrjFJ3FDd0bwCKiZv6ZcnFSqCjq1hKOLxXNQDVB
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
if ($this->isNeedAutoload()): ?>
<script type="text/javascript">
Event.observe(window, 'load', function(){
    $('template_select').value = '<?php echo $this->getLoadTemplate(); ?>';
    $('locale_select').value   = '<?php echo $this->getLoadLocale(); ?>';
    templateControl.load();
});
</script>
<?php endif; ?>