<?php
/**
 * MageWorx
 * Multi Fees Extension
 *
 * @category   MageWorx
 * @package    MageWorx_MultiFees
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-multifees"><?php echo $this->__('Manage Fees') ?></h3></td>
            <td class="form-buttons"><?php echo $this->getAddNewButtonHtml() ?></td>
	</tr>
    </table>
</div>
<?php echo $this->getGridHtml() ?>