<?php
/**
 * MageWorx
 * Multi Fees Extension
 *
 * @category   MageWorx
 * @package    MageWorx_MultiFees
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
$source = $this->getSource();
if ($source->getBaseMultifeesAmount()>0) {
    $fullInfo = $source->getDetailsMultifees();
    if ($fullInfo) $fullInfo = unserialize($fullInfo); else $fullInfo = array();

    $taxInSales = Mage::helper('mageworx_multifees')->getTaxInSales();
    $viewMode = array();
    if ($taxInSales==1) {
        $viewMode[] = false;
    } elseif ($taxInSales==2) {
        $viewMode[] = true;
    } elseif ($taxInSales==3) {
        $viewMode[] = false;
        $viewMode[] = true;
    }

    foreach ($viewMode as $inclTax) {

        foreach ($fullInfo as $fee) { 
            if (!isset($fee['tax_class_id'])) continue;
        ?>
            <tr class="multifees-details<?php if ($inclTax) echo '-inc-tax'; ?>-view" style="display:none;">
                <td class="a-right">
                    <b><?php echo $fee['title']; ?></b>
                </td>        
                <td class="a-right">
                    <b><?php echo Mage::helper('adminhtml/sales')->displayPrices($source, $inclTax?$fee['base_price']:$fee['base_price']-$fee['base_tax'], $inclTax?$fee['price']:$fee['price']-$fee['tax']); ?></b>
                </td>
            </tr>

            <?php foreach ($fee['options'] as $option) { ?>
            <tr class="multifees-details<?php if ($inclTax) echo '-inc-tax'; ?>-view" style="display:none;">
                <td class="a-right">
                    <?php echo $option['title']; ?>
                    <?php if (isset($option['percent'])) { ?>
                        (<?php echo (float)$option['percent']; ?>%)
                    <?php } ?>
                    <br />
                </td>        
                <td class="a-right">
                    <?php echo Mage::helper('adminhtml/sales')->displayPrices($source, $inclTax?$option['base_price']:$option['base_price']-$option['base_tax'], $inclTax?$option['price']:$option['price']-$option['tax']); ?>
                </td>
            </tr>
            <?php } //endforeach
        } //endforeach a-right
        ?>
        <tr <?php if (count($fullInfo)>0) { ?>class="summary-total" onclick="expandDetails(this, '.multifees-details<?php if ($inclTax) echo '-inc-tax'; ?>-view')"<?php } ?> >
            <td class="label" colspan="<?php echo $this->getColspan(); ?>">
                <div class="summary-collapse"><?php 
                    if ($taxInSales!=3) {
                        echo Mage::helper('mageworx_multifees')->__('Additional Fees');
                    } else {
                        if ($inclTax) echo Mage::helper('mageworx_multifees')->__('Additional Fees (Incl. Tax)'); else echo Mage::helper('mageworx_multifees')->__('Additional Fees (Excl. Tax)');
                    }
                ?></div>        
            </td>
            <td class="a-right"><?php echo Mage::helper('adminhtml/sales')->displayPrices($source, $inclTax?$source->getBaseMultifeesAmount():$source->getBaseMultifeesAmount()-$source->getBaseMultifeesTaxAmount(), $inclTax?$source->getMultifeesAmount():$source->getMultifeesAmount()-$source->getMultifeesTaxAmount()); ?></td>
        </tr>
    <?php } ?>
    <script type="text/javascript">
    //<![CDATA[
    //incert <div style="clear:right;"></div> by design block total
    var detailsDivs = $$('div.multifees-details');
    if (detailsDivs.length>0) {
        detailsDivs.each(function(detailsDiv){  
            var clearDiv = document.createElement('div');
            Element.extend(clearDiv);
            clearDiv.style.clear = "right";
            Element.insert(detailsDiv, {after: clearDiv});
        });
    }
    //]]>
    </script>
<?php } ?>