<?php
/**
 * MageWorx
 * Multi Fees Extension
 *
 * @category   MageWorx
 * @package    MageWorx_MultiFees
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
$img = $this->getImg();
if ($img) { ?>
    <a href="<?php echo $img->getBigImgUrl() ?>" rel="mageworxLightbox[]"><img src="<?php echo $img->getUrl() ?>" height="70" title="" class="small-image-preview v-middle" /></a>
    <?php if (Mage::app()->getRequest()->getControllerName()=='multifees_fee') { ?>
        <input class="multifees-input-del-img" type="checkbox" name="options[image_delete][<?php echo $img->getId() ?>]" value="<?php echo $img->getId() ?>" id="label-delete-img-<?php echo $img->getId() ?>" />
        <label for="label-delete-img-<?php echo $img->getId() ?>"><?php echo $this->__('Delete Image') ?></label>
    <?php } ?>
<?php } ?>