<?php
/**
 * MageWorx
 * Multi Fees Extension
 *
 * @category   MageWorx
 * @package    MageWorx_MultiFees
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
$checkoutCartBlock = $this->getParentBlock()->getParentBlock()->getChild('content')->getChild('checkout.cart');
if ($checkoutCartBlock) {
    $checkoutShippingBlock = $checkoutCartBlock->getChild('shipping');
    if ($checkoutShippingBlock) {
        $shippingMethods = $checkoutShippingBlock->getEstimateRates();
        $selectedShippingMethod = $checkoutShippingBlock->getAddressShippingMethod();
        $shippingFeeBlock = $this->getLayout()->createBlock('mageworx_multifees/fee')->setTemplate('mageworx/multifees/shipping_fee.phtml');
?>
<script type="text/javascript">
//<![CDATA[
if (typeof feeOptionImgData=='undefined') var feeOptionImgData = [];
if (typeof MultiFees!='undefined') {
<?php
foreach($shippingMethods as $code => $rates) {
    foreach($rates as $rate) { ?>
        MultiFees.addShipping('<?php echo $rate->getCode() ?>', <?php echo Zend_Json::encode($shippingFeeBlock->setCode($rate->getCode())->toHtml())?>); 
    <?php
        if ($selectedShippingMethod) { 
            if ($rate->getCode()==$selectedShippingMethod) { ?>
                MultiFees.showShipping('<?php echo $rate->getCode() ?>');
            <?php
            }
        } elseif (count($shippingMethods)==1 && count($rates)==1) { ?>
            MultiFees.showShipping('<?php echo $rate->getCode() ?>');
        <?php } ?>
    <?php } ?>
<?php } ?>
}

var estimateShippingMethodForm = $('co-shipping-method-form');
if (estimateShippingMethodForm) {
    estimateShippingMethodForm.method = 'POST';
    Element.insert(estimateShippingMethodForm, {'bottom':'<input type="hidden" name="is_estimate_shipping_fee" value="1" />'});
    var estimateShippingMethodForm = new VarienForm('co-shipping-method-form', true);
    estimateShippingMethodForm.submit = function(button, url) {        
        if (this.validator.validate()) return true;
    }.bind(estimateShippingMethodForm);
}
//]]>
</script>
<?php 
    }
} ?>