<?php
/**
 * MageWorx
 * Multi Fees Extension
 *
 * @category   MageWorx
 * @package    MageWorx_MultiFees
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
if (Mage::helper('mageworx_multifees')->isEnableShippingFees()) {
    $checkoutShippingBlock = $this->getParentBlock()->getParentBlock()->getChild('content')->getChild('checkout_shipping');
    $shippingFeeBlock = $this->getLayout()->createBlock('mageworx_multifees/fee')->setTemplate('mageworx/multifees/shipping_fee.phtml');
?>
<script type="text/javascript">
//<![CDATA[
if (typeof feeOptionImgData=='undefined') var feeOptionImgData = [];
if (typeof MultiFees!='undefined') {
<?php
foreach ($checkoutShippingBlock->getAddresses() as $index => $address) {
    $shippingMethods = $checkoutShippingBlock->getShippingRates($address);
    $selectedShippingMethod = $checkoutShippingBlock->getAddressShippingMethod($address);

    foreach($shippingMethods as $code => $rates) {
        foreach($rates as $rate) { ?>
            MultiFees.addShipping('<?php echo $address->getId(). '_' . $rate->getCode() ?>', <?php echo Zend_Json::encode($shippingFeeBlock->setCode($rate->getCode())->setAddressId($address->getId())->toHtml()) ?>);
            <?php
            if ($selectedShippingMethod) { 
                if ($rate->getCode()==$selectedShippingMethod) { ?>
                    MultiFees.showShipping('<?php echo $address->getId(). '_' .$rate->getCode() ?>');
                <?php
                }
            } elseif (count($shippingMethods)==1 && count($rates)==1) { ?>
                MultiFees.showShipping('<?php echo $address->getId(). '_' .$rate->getCode() ?>');
            <?php } ?>
        <?php } ?>
    <?php } ?>
<?php } ?>
}

var shippingMethodForm = $('shipping_method_form');
if (shippingMethodForm) {
    Element.insert(shippingMethodForm, {'bottom':'<input type="hidden" name="is_multishipping_fee" value="1" />'});
    var shippingMethodForm = new VarienForm('shipping_method_form', true);
    shippingMethodForm.submit = function(button, url) {
        if(this.validator.validate()) return true;        
    }.bind(shippingMethodForm);
}
//]]>
</script>
<?php } ?>

