<?php
/**
 * MageWorx
 * Multi Fees Extension
 *
 * @category   MageWorx
 * @package    MageWorx_MultiFees
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */

$paypalExpressReviewBlock = $this->getParentBlock()->getParentBlock()->getChild('content')->getChild('paypal.express.review');
$shippingMethods = $paypalExpressReviewBlock->getShippingRateGroups();
$shippingFeeBlock = $this->getLayout()->createBlock('mageworx_multifees/fee')->setTemplate('mageworx/multifees/shipping_fee.phtml');
?>
<script type="text/javascript">
//<![CDATA[
if (typeof feeOptionImgData=='undefined') var feeOptionImgData = [];
function initPaypalShipping() {
    if (typeof MultiFees!='undefined') {
    <?php
    foreach($shippingMethods as $code => $rates) { 
        foreach($rates as $rate) { ?>
            MultiFees.addPaypalShipping('<?php echo $rate->getCode() ?>', <?php echo Zend_Json::encode($shippingFeeBlock->setCode($rate->getCode())->toHtml())?>);
            <?php if (count($shippingMethods)==1 && count($rates)==1) { ?>
                MultiFees.showShipping('<?php echo $rate->getCode() ?>');
            <?php } else { ?>
                var shippingSelect = $('shipping_method');
                if (shippingSelect) MultiFees.showShipping(shippingSelect.value);
            <?php } ?>
        <?php } ?>
    <?php } ?>
    }
}
initPaypalShipping();

if (typeof PayPalExpressAjax!='undefined') {
    var parentUpdateShipping = PayPalExpressAjax._updateShipping.bind(PayPalExpressAjax);    
    PayPalExpressAjax._updateShipping = function() {
        parentUpdateShipping();
        initPaypalShipping();
    };
}

var shippingMethodForm = $('order_review_form');
if (shippingMethodForm) {
    Element.insert(shippingMethodForm, {'bottom':'<input type="hidden" name="is_shipping_fee" value="1" />'});
}
//]]>
</script>