<?php
                // some helpers
                $_helper = $this->helper('catalog/output');
                $storeId = Mage::app()->getStore()->getId();
                $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
                $productCount = $this->getData('num_products');

$visibility = array(
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                  );
$collection = Mage::getResourceModel('reports/product_collection')
                        ->addAttributeToSelect('*')    
                        ->setStoreId($storeId)
                        ->addStoreFilter($storeId)    
                        ->addAttributeToFilter('visibility', $visibility)             
                        ->setPageSize($productCount);
Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($collection);


/* To display product by category id */
  if($categoryId=$this->getData('category_id')){
        $category = Mage::getModel('catalog/category')->load($categoryId);
        $collection->addCategoryFilter($category);
      } ?>

  <div class="featured-pro container wow bounceInUp animated">
    <div class="slider-items-products">
        <?php     // if no products are in list, display some text
                 if (!$collection->count()) :
        ?>
        <p class="note-msg"><?php echo $this->__('There are no products at the moment.') ?></p>
        <?php else : ?>

     <?php if($categoryId=$this->getData('category_id')) { 
              $category = Mage::getModel('catalog/category')->load($categoryId);
      ?>
        <div class="new_title center"><h2><?php echo $category->getName() ?></h2></div>
    <?php } else { ?>
        <div class="new_title center"><h2><?php echo $this->__('Category List') ?></h2></div>
    <?php } ?>

   
<div id="best-seller-slider" class="product-flexslider hidden-buttons">
    <div class="slider-items slider-width-col4 products-grid">    
        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 4;
                $i = 0;                
                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());

        ?>
        <?php if ($i++%$_columnCount==0): ?>            
        <?php endif ?>
<div class="item">
   <div class="item-inner">
     <div class="item-img">
       <div class="item-img-info">
         <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>"></a> 
         <?php echo $this->helper('fabiasettings')->getLabel($_product);  ?>
         <?php  if(Mage::app()->getStore()->getConfig('fabiasettings/fabiasettings_quickview/enable')==1){?> 
              <a rel="nofollow" href="<?php echo Mage::getBaseUrl().'quickview/index/view?prodid='.$_product->getId(); ?>" data-fancybox-type="iframe" class="magik-btn-quickview quickview-btn" id="magik-btn-quickview_<?php echo $_product->getId()?>"><span><?php echo $this->__('Quick View') ?></span></a>
         <?php }  ?> 
       </div> <!--item-img-info-->
     </div> <!--item-img-->
     <div class="item-info">
       <div class="info-inner">
         <div class="item-title">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                  <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                  if(strlen($prod_name) > 17) {echo substr($prod_name,0,17)."...";}else {echo $prod_name;}?>
             </a>
         </div> <!--item-title-->
         <div class="item-content">
            <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
            <?php } else { ?>  
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
            <?php } ?>
            <div class="item-price"><?php echo $this->getPriceHtml($_product, true) ?></div>
            <div class="actions">
              <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"></a>
             <div class="add_cart">         
              <?php if($_product->isSaleable()): ?>
                <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
              <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
              <?php endif; ?>          
             </div> <!--add_cart-->
             <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare');?>"></a>
             <?php endif; ?>
          </div> <!--actions-->
         </div><!--item-content-->
       </div><!--info-inner-->
     </div> <!--item-info-->                   
   </div> <!--item-inner-->
</div> <!--item-->      
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>            
            <?php endif ?>
            
                <?php endforeach ?>
      </div>    
    </div> 
 
        <?php endif ?>  <!--Endif !$collection->count() -->
    </div> <!--slider-items-products-->
  </div> <!--featured-pro container wow bounceInUp animated-->



