<?php
                // some helpers
                $_helper = $this->helper('catalog/output');
                $storeId = Mage::app()->getStore()->getId();
                $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
                $productCount = $this->getData('num_products');

$visibility = array(
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                  );
$collection = Mage::getResourceModel('reports/product_collection')
                        ->addAttributeToSelect('*')    
                        ->setStoreId($storeId)
                        ->addStoreFilter($storeId)    
                        ->addAttributeToFilter('visibility', $visibility)             
                        ->setPageSize(1);
Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($collection);

  $prodid1 = $this->getData('fabia_category_product_id');

/* To display product by category id */
  if($categoryId=$this->getData('category_id')){
        $category = Mage::getModel('catalog/category')->load($categoryId);
        $collection->addCategoryFilter($category);
      }
                // if no products are in list, display some text
                 if (!$collection->count()) :
        ?>
        <p class="note-msg"><?php echo $this->__('There are no products at the moment.') ?></p>
        <?php else : ?>

<div class="header-nav-dropdown-wrapper clearer">    
      
        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 3;
                $i = 0;                
                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($prodid1);

        ?>
        <?php if ($i++%$_columnCount==0): ?>            
        <?php endif ?>

<div class="nav-block nav-block-right std grid12-4 <?php if(($i-1)%$_columnCount==0): ?>first<?php elseif($i%$_columnCount==0): ?> last<?php elseif($i%$_columnCount!==0): ?> odd<?php endif; ?>">
  <div class="cat_pr_info">
    <div class="cat_img">
      <img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(175,200) ?>">
    </div> <!--cat_img-->
    <div class="products-info">
      <div class="pr-title">
         <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                  <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                  if(strlen($prod_name) > 30) {echo substr($prod_name,0,30)."...";}else {echo $prod_name;}?>
         </a>
      </div> <!--pr-title-->
      <?php echo $this->getPriceHtml($_product, true) ?>
      <div class="push_text">
         <?php $prod_desc = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
               if(strlen($prod_desc) > 40) {echo substr($prod_desc,0,40)."...";}else {echo $prod_desc;}
         ?>
      </div>
      <div class="cat-bnt">
         <?php if($_product->isSaleable()): ?>
               <button type="button" title="<?php echo $this->__('BUY IT NOW') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('BUY IT NOW') ?></span></button>            
         <?php else: ?>
               <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
         <?php endif; ?> 
      </div> <!--cat-bnt-->
    </div> <!--products-info-->
  </div> <!--cat_pr_info-->
</div> <!--nav-block nav-block-right grid12-5-->      
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>            
            <?php endif ?>
            
                <?php endforeach ?>
 
</div> <!--header-nav-dropdown-wrapper clearer-->

        <?php endif ?>  <!--Endif !$collection->count() -->



