
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>

<?php $config1 = Mage::getStoreConfig('web/default/cms_home_page'); ?>

<?php if(($config1=='fabia_home_one')) { ?>   
  <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_two')) { ?> 
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />  
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider2.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_three')) { ?>   
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider3.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu3.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_four')) { ?>   
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme4.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu4.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_five')) { ?>   
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider5.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap_2.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common5.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_six') or ($config1=='brasil_home') or ($config1=='peru_home') or ($config1=='espana_home')) { ?>   
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style6.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider6.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme6.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu6.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_seven')) { ?>   
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap7.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style7.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider7.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme7.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/jquery.mobile-menu.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common7.js" type="text/javascript"></script>
<?php } ?>

<?php if(($config1=='fabia_home_eight')) { ?>   
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style8.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider8.css" type="text/css" />
   <link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme8.css" type="text/css" />

   <script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
   <script src="<?php echo $this->getSkinUrl(); ?>js/common8.js" type="text/javascript"></script>
<?php } ?>



</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?> rtl">
  <div id="page">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>      
      
      <?php echo $this->getChildHtml('header') ?>


    <?php if(($config1=='fabia_home_four')) { ?>
       <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home4_header_block')->toHtml() ?>
    <?php } ?>

       <?php echo $this->getChildHtml('breadcrumbs') ?>
<!-- BEGIN Main Container -->  
      <?php if(($config1=='fabia_home_five')) { ?>
        <section class="main-container col1-layout">
      <?php } else {?>    
       <div class="main-container col1-layout wow bounceInUp animated">     
       <?php } ?>       
	       <div class="main container">                     
              <?php echo $this->getChildHtml('global_messages') ?>
              <?php echo $this->getChildHtml('content') ?>          
	       </div><!--main-container-->
         <?php if(($config1=='fabia_home_five')) { ?>
          </section>
         <?php }else{?> 
          </div> <!--col1-layout-->
          <?php } ?>

<?php if(($config1!='fabia_home_four')&&($config1!='fabia_home_five')&&($config1!='fabia_home_seven')&&($config1!='fabia_home_eight')) { ?>  <!-- exclude Form version 4, 5, 7, 8 -->
 

  <?php if(($config1=='fabia_home_six')) { ?>  
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_offer_bottom_banner_block')->toHtml() ?>
  <?php } ?>

  <?php  if(($config1=='brasil_home')) { ?>  
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_offer_bottom_banner_block_brasil')->toHtml() ?>
  <?php } ?>
  <?php if(($config1=='peru_home')) { ?>  
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_offer_bottom_banner_block_peru')->toHtml() ?>
  <?php } ?>
  <?php if(($config1=='espana_home')) { ?>  
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_offer_bottom_banner_block_espana')->toHtml() ?>
  <?php } ?>
 


<?php } ?>
<?php if(($config1=='fabia_home_five')) { ?>  <!-- For version 5 -->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home5_offer_bottom_banner_block')->toHtml() ?>
<?php } ?>
     
              <?php echo $this->getChildHtml('footer') ?>
              <?php echo $this->getChildHtml('before_body_end') ?>
              <?php echo $this->getAbsoluteFooter() ?> 
  </div> <!--page-->

<!-- Mobile Menu-->
<?php if(($config1!='fabia_home_five')&&($config1!='fabia_home_eight')) { ?> <!-- Exclude from version 5 & 8 -->
<div id="mobile-menu">
  <?php if($config1=='fabia_home_seven') { ?> <!-- For version 7 -->
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini-mob.phtml')->toHtml() ; ?>
  <?php } ?>
  <ul class="mobile-menu">
    <?php echo $this->getLayout()->createBlock('catalog/navigation')->setTemplate('catalog/navigation/top_nav_mob.phtml')->toHtml() ; ?>
  </ul> <!--mobile-menu-->
</div>
<?php } ?> <!-- End Exclude from version 5 & 8 -->

</body>
</html>