
<?php
/**
 * Template for Mage_Page_Block_Html
   */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style5.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider5.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/full-slider.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme.css" type="text/css" />
<script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap_2.min.js" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl(); ?>js/common5.js" type="text/javascript"></script>

</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?> index-home" itemscope itemtype="http://schema.org/WebPage">
  
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>      

    <header id="myCarousel" class="carousel slide">
      <div class="main-header">
        <?php echo $this->getChildHtml('header') ?> 
      </div>
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home5_slider_banner_block')->toHtml(); ?>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"> <span class="icon-prev"></span> </a> <a class="right carousel-control" href="#myCarousel" data-slide="next"> <span class="icon-next"></span> </a> 

    </header>


<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/footer1.phtml')->toHtml(); ?>
      <?php echo $this->getChildHtml('before_body_end') ?>
      <?php echo $this->getAbsoluteFooter() ?> 

      <script type='text/javascript'>
    
    jQuery('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    
        </script>



</body>
</html>
