
<?php
/**
 * Template for Mage_Page_Block_Html
  */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/style8.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/revslider8.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/owl.theme8.css" type="text/css" />

<script src="<?php echo $this->getSkinUrl(); ?>js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl(); ?>js/common8.js" type="text/javascript"></script>
<script type='text/javascript'>
        jQuery(document).ready(function(){
            jQuery('#rev_slider_4').show().revolution({
                dottedOverlay: 'none',
                delay: 5000,
                startwidth: 1150,
                startheight: 530,

                hideThumbs: 200,
                thumbWidth: 200,
                thumbHeight: 50,
                thumbAmount: 2,

                navigationType: 'thumb',
                navigationArrows: 'solo',
                navigationStyle: 'round',

                touchenabled: 'on',
                onHoverStop: 'on',
                
                swipe_velocity: 0.7,
                swipe_min_touches: 1,
                swipe_max_touches: 1,
                drag_block_vertical: false,
            
                spinner: 'spinner0',
                keyboardNavigation: 'off',

                navigationHAlign: 'center',
                navigationVAlign: 'bottom',
                navigationHOffset: 0,
                navigationVOffset: 20,

                soloArrowLeftHalign: 'left',
                soloArrowLeftValign: 'center',
                soloArrowLeftHOffset: 20,
                soloArrowLeftVOffset: 0,

                soloArrowRightHalign: 'right',
                soloArrowRightValign: 'center',
                soloArrowRightHOffset: 20,
                soloArrowRightVOffset: 0,

                shadow: 0,
                fullWidth: 'on',
                fullScreen: 'off',

                stopLoop: 'off',
                stopAfterLoops: -1,
                stopAtSlide: -1,

                shuffle: 'off',

                autoHeight: 'off',
                forceFullWidth: 'on',
                fullScreenAlignForce: 'off',
                minFullScreenHeight: 0,
                hideNavDelayOnMobile: 1500,
            
                hideThumbsOnMobile: 'off',
                hideBulletsOnMobile: 'off',
                hideArrowsOnMobile: 'off',
                hideThumbsUnderResolution: 0,

                hideSliderAtLimit: 0,
                hideCaptionAtLimit: 0,
                hideAllCaptionAtLilmit: 0,
                startWithSlide: 0,
                fullScreenOffsetContainer: ''
            });
        });
        </script>
</head>

<body class="<?php echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?> rtl" itemscope itemtype="http://schema.org/WebPage">
  <div id="page">
    
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>      
    <?php echo $this->getChildHtml('header') ?> 
<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/header1.phtml')->toHtml(); ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home8_offer_bottom_banner_block')->toHtml() ?>

    <!-- Home slider -->
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home8_slider_banner_block')->toHtml() ?>   
        
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('fabia_home8_offer_banner_block')->toHtml() ?>
               
      <div class="main-col"> 
        <div class="container">    
          <div class="row">    
            <div class="product-grid-view">   
              <div class="col-md-12">                
                <?php echo $this->getChildHtml('breadcrumbs') ?>               
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
              </div> <!--col-md-12-->
            </div><!--product-grid-view-->
          </div><!--row-->
        </div><!--container-->
      </div><!--main-col-->

      <?php echo $this->getChildHtml('footer') ?> 
      <?php echo $this->getChildHtml('before_body_end') ?>
      <?php echo $this->getAbsoluteFooter() ?>     

      </div> <!--page-->
      
      <?php  if(Mage::app()->getStore()->getConfig('fabiasettings/fabiasettings_newsletterpopup/newsletterpopup_enable')==1){?>
          <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_home_popup.phtml')->toHtml() ; ?>
      <?php }  ?>

</body>
</html>