<?php $config1 = Mage::getStoreConfig('web/default/cms_home_page'); ?>

<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="block block-list block-compared">
    <div class="block-title">
        <?php if(($config1=='fabia_home_five')) { ?>
            <span><?php echo $this->__('Recently Compared') ?></span>
        <?php }else{?>   
            <?php echo $this->__('Recently Compared') ?>
        <?php } ?>
    </div>
    <div class="block-content">
        <ol id="recently-compared-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
              <p class="product-name">
                <a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a>
              </p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-compared-items');</script>
    </div>
</div>
<?php endif; ?>