<?php echo $this->getChildHtml('extraCss'); ?>
<?php echo $this->getChildHtml('extrajs'); ?>
<?php echo $this->getChildHtml('login_webpos') ?>
<?php echo $this->getChildHtml('popup_webpos'); ?>
<!--<a id = 'test' data-text="Click or bookmark" style="display: none"
   href="
javascript:void((function(d){if(self!=top||d.getElementById('toolbar')&amp;&amp;d.getElementById('toolbar').getAttribute('data-resizer'))return false;d.write('&lt;!DOCTYPE HTML&gt;&lt;html style=&quot;opacity:0;&quot;&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;&lt;/head&gt;&lt;body&gt;&lt;Small Tablet&lt;/a&gt;&lt;a data-viewport=&quot;768x1024&quot; data-icon=&quot;tablet&quot;&gt;Tablet (e.g. Apple iPad 2-3rd, mini)&lt;/a&gt;&lt;a data-viewport=&quot;1280x800&quot; data-icon=&quot;notebook&quot;&gt;Widescreen&lt;/a&gt;&lt;script src=&quot;<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'/magestore/webpos/resizer.js'; ?>&quot;&gt;&lt;/script&gt;&lt;/body&gt;&lt;/html&gt;')})(document));" class="button primary">
</a>
<script>
    var href = $D('#test').attr('href');
    window.location.href = href;

</script>-->
<div class="bg-create-customer" style="display: none"  onclick="hidePopupCustomer()"></div>
<div id="create-customer" class="modal">
    <?php echo $this->getChildHtml('create_customer_webpos'); ?>
</div>
<div id="bg-shipping-address" style="display: none"  onclick="cancelEditAddress();"></div>
<div id="shipping-address" class="modal">
    <?php echo $this->getChildHtml('shipping_webpos'); ?>
</div>
<div id='pos_container'>
    <div id='main_container' class='row'>
        <div id='menu' class='menuHide'>
            <?php echo $this->getChildHtml('menu_webpos'); ?>
        </div>
        <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 col_left" id="product-left">
            <div id='col_left_loader'>
                <div class="img-ajax"></div>
                <div class='loading_message'>
                    <?php echo $this->__('Loading product information'); ?>
                </div>
            </div>
            <div id='col_left_firsttime_loader'>
                <div class="img-ajax"></div>
                <div class='loading_message'>
                    <?php echo $this->__('Loading products information for the first time use, this may take a few minute. Please wait...'); ?>
                    <div id='loading_status'></div>
                </div>
            </div>
            <div class='top_bar left'>
                <div class="incon-menu col-lg-1 col-md-1 col-sm-1 col-xs-1">
                    <img onclick="showHideMenu('checkout')" id='showmenu_icon' class='pointerCursor' src='<?php echo $this->getSkinUrl('images/icon/menu.png'); ?>'/>
                </div>
                <div class='top_bar_right col-lg-11 col-md-11 col-sm-11 col-xs-11'>
                    <div class='category col-lg-6 col-md-6 col-sm-6 col-xs-6 ' id='category_area'>
                        <?php echo $this->getChildHtml('menu_webpos_category'); ?>
                    </div>
                    <div class='product_search col-lg-6 col-md-6 col-sm-6 col-xs-6 width10percentage' id='product_search_area'>
                        <img onclick="showSearchForm()" id='search_icon' class='pointerCursor' src='<?php echo $this->getSkinUrl('images/icon/search.png'); ?>' />
                    </div>
                    <div class='product_search col-lg-11 col-md-11 col-sm-11 col-xs-11 hide ' id="product_search">
                        <form id="product_search_form" action="" method="" onsubmit="return false;">
                            <input  onchange="searchProduct();"  type="text" class="form-control" placeholder='<?php echo $this->__('Enter search terms or scan barcodes'); ?>' id="product_search_keyword" name="keyword"/>

                            <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">

                            </span>
                        </form>
                    </div>
                    <div onclick="cancelSearch()" class='col-lg-1 col-md-1 col-sm-1 col-xs-1 pointerCursor hide' id='cancel_search_icon'>
                        <img src='<?php echo $this->getSkinUrl('images/icon/cancel.png'); ?>' />
                    </div>
                    <div id="global_search_autocomplete" class="autocomplete" style="z-index:10;overflow-y:auto;max-height:450px; width: 98% !important"></div>
                </div>
                <div class='clear'></div>
            </div>
            <div class='col_content_left'>
                <div id='content' onscroll="loadMoreProduct()">
                    <div id='product_content'>
                    </div>
                </div>                
                <div class="customer-sale" style="display: none">
                    <?php echo $this->getChildHtml('customer_sale'); ?>
                </div>
            </div>

            <div class='footer '>
                <div class="footer-content">
                    <div class='col-lg-5 col-md-5 col-sm-5 col-xs-5' id=''>

                        <div id='numberProduct'> 
                            <?php
                            $numberProduct = Mage::getModel('core/session')->getData('numberProduct');
                            echo $this->__("Totals: " . $numberProduct . ' products');
                            ?>
                        </div>

                        <div id="offline">
                            <button id="mode_status" class='nowonline' onclick="changeOffline(this)" value='on'>Online</button>
                            <input id="network_status" value='on' type='hidden'/>
                        </div>
                        <div id='status'></div>

                    </div>

                    <div class='col-lg-2 col-md-2 col-sm-2 col-xs-2' id='productPager' style="padding: 0;">

                        <ul class="pager" style='<?php if ($numberProduct <= 16) echo 'display:none;'; ?>'>
                            <li><a href="#" id='bt_previous_product_page' onclick="reloadListProduct('back', 0, '')"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a></li>
                            <li><a href="#" id='bt_next_product_page' onclick="reloadListProduct('next', 0, '')"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a></li>
                        </ul>
                    </div>
                    <div id="customer-sale-btn" class='col-lg-5 col-md-5 col-sm-5 col-xs-5'>
                        <button   onclick="showCustomersale()" type="button" class="btn"><?php echo $this->__('Custom Sale'); ?></button>
                    </div>
                    <div id="cancel-sale-btn" class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="display: none">
                        <button onclick="cancelCustomersale()" type="button" class="btn"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span><span><?php echo $this->__('Cancel'); ?></span></button>
                    </div>

                </div>

            </div>

        </div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 col_right" id="total-right">
            <div id='col_right_loader'>
                <div class="img-ajax"></div>
            </div>
            <div class='top_bar'>
                <img title="Empty Cart" id='customer_loader' class='pointerCursor' onclick="emptyCart(empty_cart_url);" src='<?php echo $this->getSkinUrl('images/icon/clear.png'); ?>'/>
                <?php
                $numberItem = Mage::helper('checkout/cart')->getSummaryCount();
                if ($numberItem != '' && $numberItem > 0) {
                    $numberItem = Mage::helper('checkout/cart')->getSummaryCount();
                } else {
                    $numberItem = 0;
                }
                ?>
                <h2 class="title-cart">Cart(<span id="total_number_item"><?php echo $numberItem; ?></span>)</h2>
                <img onclick="showCategory()" id='continue_select_product' class='pointerCursor hide' src='<?php echo $this->getSkinUrl('images/icon/back.png'); ?>'/>
                <div class='top_bar_right'>
                    <img title="Add Order Comment" onclick="showhideOrderCommnent('order-comment');" id='customer_edit_icon' class='pointerCursor' src='<?php echo $this->getSkinUrl('images/icon/order_comment.png'); ?>' />                    
                </div>                                
                <div class='clear'></div>
                <div class="order-comment" id="order-comment" style="display: none">
                    <div class="comment">
                        <div class="col col-lg-7 col-md-7 col-sm-7 col-xs-7"><?php echo $this->__('Order Comment:'); ?></div>
                        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5" style="padding:0"><button class="btn btn-warning" onclick="saveOrderComment();" style="float: right;margin-left: -11px;">Save</button></div>                                            
                        <form>
                            <textarea id="order-comment-content"></textarea>
                        </form>
                    </div>                    
                </div>
            </div>
            <div class='col_content_right' id='cart_webpos_area'>
                <div id='cart_webpos'>
                    <?php echo $this->getChildHtml('cart_webpos'); ?>
                </div>
            </div>
            <div class='footer'>
                <?php
                $quote = Mage::getModel('checkout/cart')->getQuote();
                $items = $quote->getAllItems();
                ?>
                <div id='footer_right_overlay' class='<?php if (count($items) > 0) echo 'hide'; ?>'></div>
				<!-- Changed By Tuan bun (27/08/2015): save payment after savecart -->
                <div onclick="saveCart(function(){webpos_save_data(save_data_url,'payment')})" id='bt_checkout' class='pointerCursor'>
				<!-- Changed By Tuan bun (27/08/2015): save payment after savecart -->
                    <div class='label'><?php echo $this->__('Checkout'); ?></div>
                    <div class='value'>
                        <div class='' id='webpos_subtotal_button'>
                            <?php
                            echo Mage::app()->getStore()->formatPrice($quote->getGrandTotal());
                            ?>                            
                        </div>
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    </div>
                    <div class='clear'></div>
                </div>
                <div class='clear'></div>
            </div>
        </div>
        <div id='order_info' class='orderHide'>
            <div id='checkout_loader'>
                <div class="img-ajax"></div>
            </div>
            <?php echo $this->getChildHtml('orderinfo_webpos'); ?>
        </div>
    </div>
    <div id='orders_area' class='mainContainer'>
        <?php echo $this->getChildHtml('order_area'); ?>
    </div>
    <div id='settings_area' class='mainContainer'>
        <?php echo $this->getChildHtml('setting_area'); ?>
    </div>
</div>